### ISSUE TITLE
cli for whitelisting

### ISSUE THREAD

**Issue by ryandawsonuk** [arrikto/oidc-authservice#15]
We've got Go cobra code that makes it easy to add paths to the whitelisting env var. I wrote this because I want to whitelist paths programmatically from a shell script and I couldn't find any bash way to do it. Would like to be able to contribute it somewhere. Would it fit in kfctl? Or would it be worth having a ctl specifically for the auth service? Or perhaps mine is just a fringe use-case?

**Comment by yanniszark** [comment]
@ryandawsonuk do you need to whitelist paths dynamically?
Or do you know them beforehand?
If you know them beforehand, why not use the SKIP_AUTH_URI option in your KfDef?

**Comment by ryandawsonuk** [comment]
I actually didn't notice that option! Yeah I do know them in advance. That is a good option! I'll close this and try that and come back if I have any problems.
