### ISSUE TITLE
oidc-authservice panics when using Azure as OIDC provider

### ISSUE THREAD

**Issue by aminGwork** [arrikto/oidc-authservice#19]
I've been trying to get kubeflow working with Azure AD as an idenity provider for a few weeks now with no success.  Through some digging i've stumbled on this error that is logged by the service when the code response comes back from AAD prior to the token phase.
I've tried running this image 28c59ef and 5522e4d
Here is the error. 

'2020/04/23 21:02:51 http: panic serving 10.215.17.77:39910: interface conversion: interface {} is nil, not string
goroutine 46 [running]:
net/http.(*conn).serve.func1(0xc0002f1540)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x7b27c0, 0xc000134e10)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
main.(*server).callback(0xc000496000, 0x8b5c20, 0xc00047dc00, 0xc000168f00)
        /go/src/oidc-authservice/handlers.go:141 +0x1059
net/http.HandlerFunc.ServeHTTP(0xc000238070, 0x8b5c20, 0xc00047dc00, 0xc000168f00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000212000, 0x8b5c20, 0xc00047dc00, 0xc0000ef000)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0001e8120, 0x8b5c20, 0xc00047dc00, 0xc0000ef000)
        /go/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:54 +0x1037
net/http.serverHandler.ServeHTTP(0xc000284b60, 0x8b5c20, 0xc00047dc00, 0xc0000ef000)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0002f1540, 0x8b69e0, 0xc0004cdd80)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2927 +0x38e
'

**Comment by yanniszark** [comment]
Hi @aminGwork! The OIDC AuthService tries to find the user id in a field (claim) inside the JWT provided by your OIDC Provider (Azure).
This is configured with the `USERID_CLAIM` variable and the default is `email`.
My guess is that your provider doesn't put the `email` field in the JWT. I would suggest looking into that.
As for the cryptic message, I have opened https://github.com/arrikto/oidc-authservice/issues/18 to improve it.

**Comment by yanniszark** [comment]
@aminGwork have you resolved your issue with the information above ^? :)

**Comment by awassink** [comment]
I ran into the same issue and can confirm that the missing email field was the issue in my case. In Azure the email field is an optional field. Once set properly in the user profile authentication worked fine. 
The referenced kubeflow issue is related to this issue.

**Comment by athamark** [comment]
I am closing this issue since configuring Azure AD to include the `email` field resolves the problem. So let's keep a note of it: "When integrating AuthService with Azure AD as the external Identity Provider ensure that you have selected the `email` optional field."
