### ISSUE TITLE
Arrikto with Istio and Dex for Kubeflow

### ISSUE THREAD

**Issue by gettheguru** [arrikto/oidc-authservice#30]
Hi,

I am working on integrated Kubeflow for Azure AD, and I came across their implementation which uses your auth service.

I have largely followed the implementation except I had to update the container image they were pulling from your repo so that I could use the custom CA_BUNDLE for the dex service.

It feels like everything is almost there, I get through Azure AD, but the callback appears to be the function that's not working, because on the reply URL from Azure AD, I basically get back to the first authentication again.

I believe I am falling over on the 'AUTHSERVICE_URL_PREFIX' option which wasn't something that existed in the image they use in the Kubeflow examples. Could you advise what this should be?

**Comment by gettheguru** [comment]
Resolved using earlier container image and instead using the cert in the system store through k8s mounts.

**Comment by sudivate** [comment]
@gettheguru  I'm trying to achieve the same with AKS and Azure AD, can you please share which earlier image for used ? or point to sample manifest that you have?
