### ISSUE TITLE
AuthService assumes tokens are expired when the UserInfo call fails

### ISSUE THREAD

**Issue by apyrgio** [arrikto/oidc-authservice#32]
While performing some tests on a long living session with strict session validation enabled, we noticed that requests started to fail after some point. We believe the reason was the following:

1. The client probably closed the TCP connection after sending a request. This can happen if a browser sends a request and gets immediately interrupted, e.g., due to a refresh.
2. The server detected the closed connection and send a cancellation signal to the context.
3. The goroutine that was querying the user info got cancelled midway.
4. We interpreted the failure to get the user info as an expired token, and we deleted the session. Unfortunately, we can't have an accurate description of the error, because the `go-oidc` library does not permit this (see: https://github.com/coreos/go-oidc/issues/248).

We should properly detect the reason why the user info call fails, and delete the session only when we are positive that the token has expired.

**Comment by yanniszark** [comment]
Closing with PR: https://github.com/arrikto/oidc-authservice/pull/31
