### ISSUE TITLE
Support specifying a custom CA

### ISSUE THREAD

**Issue by yanniszark** [arrikto/oidc-authservice#9]
There are cases where a user's OIDC Provider is using a self-signed certificate.
In those cases, we want the user to be able to specify the custom CA in the oidc-authservice, so that it will trust it.

**Comment by hemantha-kumara** [comment]
@yanniszark is there any plan to support this issue?  we are facing this issue right now where OIDC provider is using self-signed certs

`time="2020-04-17T12:49:23Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: Get https://apigw.dsml-csfp-2/auth/realms/ccsp-apcore/.well-known/openid-configuration: x509: certificate signed by unknown authority"`

**Comment by yanniszark** [comment]
Hi @hemantha-kumara!
We'd like to add this functionality with the `CA_BUNDLE` envvar, which points to a file where the custom cert is stored.
Implementation should be straightforward, passing the right context into the Provider constructor.
We haven't had the time to implement this yet, however contributions are welcome!
